// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMD7XyRo_TO-bikl7w71DiCJZmF4AkVw',
    appId: '1:400236783147:web:a2d35c1b76d3280e36ec6e',
    messagingSenderId: '400236783147',
    projectId: 'hkecomm-5a354',
    authDomain: 'hkecomm-5a354.firebaseapp.com',
    storageBucket: 'hkecomm-5a354.firebasestorage.app',
    measurementId: 'G-BW3W3PH2EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHBLBanwghXvsCUJh4z7fYz31Wq8k9lD8',
    appId: '1:400236783147:android:1bc7272482463dfa36ec6e',
    messagingSenderId: '400236783147',
    projectId: 'hkecomm-5a354',
    storageBucket: 'hkecomm-5a354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qrgaWIluIvBvguZnIQTUR5IvQOV0xcY',
    appId: '1:400236783147:ios:b7d1fc33737ecc9236ec6e',
    messagingSenderId: '400236783147',
    projectId: 'hkecomm-5a354',
    storageBucket: 'hkecomm-5a354.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceWithFirebase',
  );
}
